/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISnapshot__factory } from "./ISnapshot__factory";
export { Roles__factory } from "./Roles__factory";
export { Snapshottable__factory } from "./Snapshottable__factory";
