/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ResolutionManager } from "./ResolutionManager";
export type { ResolutionManagerBase } from "./ResolutionManagerBase";
