/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as internalMarket from "./InternalMarket";
import type * as priceOracle from "./PriceOracle";
import type * as resolutionManager from "./ResolutionManager";
import type * as shareholderRegistry from "./ShareholderRegistry";
import type * as telediskoToken from "./TelediskoToken";
import type * as voting from "./Voting";
import type * as extensions from "./extensions";
import type * as mocks from "./mocks";

export type { internalMarket };

export type { priceOracle };

export type { resolutionManager };

export type { shareholderRegistry };

export type { telediskoToken };

export type { voting };

export type { extensions };

export type { mocks };
