/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

import type { OnEvent, PromiseOrValue, TypedEvent, TypedEventFilter, TypedListener } from "../../common";

export interface IShareholderRegistryInterface extends utils.Interface {
  functions: {
    "CONTRIBUTOR_STATUS()": FunctionFragment;
    "INVESTOR_STATUS()": FunctionFragment;
    "MANAGING_BOARD_STATUS()": FunctionFragment;
    "SHAREHOLDER_STATUS()": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "balanceOfAt(address,uint256)": FunctionFragment;
    "getStatus(address)": FunctionFragment;
    "getStatusAt(address,uint256)": FunctionFragment;
    "isAtLeast(bytes32,address)": FunctionFragment;
    "isAtLeastAt(bytes32,address,uint256)": FunctionFragment;
    "snapshot()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "totalSupplyAt(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CONTRIBUTOR_STATUS"
      | "INVESTOR_STATUS"
      | "MANAGING_BOARD_STATUS"
      | "SHAREHOLDER_STATUS"
      | "balanceOf"
      | "balanceOfAt"
      | "getStatus"
      | "getStatusAt"
      | "isAtLeast"
      | "isAtLeastAt"
      | "snapshot"
      | "totalSupply"
      | "totalSupplyAt",
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "CONTRIBUTOR_STATUS", values?: undefined): string;
  encodeFunctionData(functionFragment: "INVESTOR_STATUS", values?: undefined): string;
  encodeFunctionData(functionFragment: "MANAGING_BOARD_STATUS", values?: undefined): string;
  encodeFunctionData(functionFragment: "SHAREHOLDER_STATUS", values?: undefined): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [PromiseOrValue<string>]): string;
  encodeFunctionData(
    functionFragment: "balanceOfAt",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: "getStatus", values: [PromiseOrValue<string>]): string;
  encodeFunctionData(
    functionFragment: "getStatusAt",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: "isAtLeast",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: "isAtLeastAt",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: "snapshot", values?: undefined): string;
  encodeFunctionData(functionFragment: "totalSupply", values?: undefined): string;
  encodeFunctionData(functionFragment: "totalSupplyAt", values: [PromiseOrValue<BigNumberish>]): string;

  decodeFunctionResult(functionFragment: "CONTRIBUTOR_STATUS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "INVESTOR_STATUS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MANAGING_BOARD_STATUS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SHAREHOLDER_STATUS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOfAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStatusAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAtLeast", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAtLeastAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "snapshot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalSupply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalSupplyAt", data: BytesLike): Result;

  events: {};
}

export interface IShareholderRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IShareholderRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CONTRIBUTOR_STATUS(overrides?: CallOverrides): Promise<[string]>;

    INVESTOR_STATUS(overrides?: CallOverrides): Promise<[string]>;

    MANAGING_BOARD_STATUS(overrides?: CallOverrides): Promise<[string]>;

    SHAREHOLDER_STATUS(overrides?: CallOverrides): Promise<[string]>;

    balanceOf(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[BigNumber]>;

    balanceOfAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    getStatus(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[string]>;

    getStatusAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    isAtLeast(
      status: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    isAtLeastAt(
      status: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    snapshot(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupplyAt(snapshotId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  CONTRIBUTOR_STATUS(overrides?: CallOverrides): Promise<string>;

  INVESTOR_STATUS(overrides?: CallOverrides): Promise<string>;

  MANAGING_BOARD_STATUS(overrides?: CallOverrides): Promise<string>;

  SHAREHOLDER_STATUS(overrides?: CallOverrides): Promise<string>;

  balanceOf(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

  balanceOfAt(
    account: PromiseOrValue<string>,
    snapshotId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  getStatus(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<string>;

  getStatusAt(
    account: PromiseOrValue<string>,
    snapshotId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<string>;

  isAtLeast(
    status: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  isAtLeastAt(
    status: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    snapshotId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  snapshot(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupplyAt(snapshotId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    CONTRIBUTOR_STATUS(overrides?: CallOverrides): Promise<string>;

    INVESTOR_STATUS(overrides?: CallOverrides): Promise<string>;

    MANAGING_BOARD_STATUS(overrides?: CallOverrides): Promise<string>;

    SHAREHOLDER_STATUS(overrides?: CallOverrides): Promise<string>;

    balanceOf(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    balanceOfAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getStatus(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<string>;

    getStatusAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<string>;

    isAtLeast(
      status: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    isAtLeastAt(
      status: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    snapshot(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupplyAt(snapshotId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    CONTRIBUTOR_STATUS(overrides?: CallOverrides): Promise<BigNumber>;

    INVESTOR_STATUS(overrides?: CallOverrides): Promise<BigNumber>;

    MANAGING_BOARD_STATUS(overrides?: CallOverrides): Promise<BigNumber>;

    SHAREHOLDER_STATUS(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    balanceOfAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getStatus(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    getStatusAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isAtLeast(
      status: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isAtLeastAt(
      status: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    snapshot(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupplyAt(snapshotId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    CONTRIBUTOR_STATUS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    INVESTOR_STATUS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MANAGING_BOARD_STATUS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SHAREHOLDER_STATUS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOf(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOfAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getStatus(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStatusAt(
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isAtLeast(
      status: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isAtLeastAt(
      status: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      snapshotId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    snapshot(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupplyAt(snapshotId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
