/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVoting } from "./IVoting";
export type { Voting } from "./Voting";
export type { VotingBase } from "./VotingBase";
export type { VotingSnapshot } from "./VotingSnapshot";
