/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { EventFragment, FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

import type { OnEvent, PromiseOrValue, TypedEvent, TypedEventFilter, TypedListener } from "../../common";

export interface VotingBaseInterface extends utils.Interface {
  functions: {
    "afterTokenTransfer(address,address,uint256)": FunctionFragment;
    "canVote(address)": FunctionFragment;
    "delegate(address)": FunctionFragment;
    "getDelegate(address)": FunctionFragment;
    "getTotalVotingPower()": FunctionFragment;
    "getVotingPower(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "afterTokenTransfer"
      | "canVote"
      | "delegate"
      | "getDelegate"
      | "getTotalVotingPower"
      | "getVotingPower",
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "afterTokenTransfer",
    values: [PromiseOrValue<string>, PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: "canVote", values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: "delegate", values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: "getDelegate", values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: "getTotalVotingPower", values?: undefined): string;
  encodeFunctionData(functionFragment: "getVotingPower", values: [PromiseOrValue<string>]): string;

  decodeFunctionResult(functionFragment: "afterTokenTransfer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delegate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDelegate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTotalVotingPower", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVotingPower", data: BytesLike): Result;

  events: {
    "DelegateChanged(address,address,address)": EventFragment;
    "DelegateVotesChanged(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DelegateChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DelegateVotesChanged"): EventFragment;
}

export interface DelegateChangedEventObject {
  delegator: string;
  currentDelegate: string;
  newDelegate: string;
}
export type DelegateChangedEvent = TypedEvent<[string, string, string], DelegateChangedEventObject>;

export type DelegateChangedEventFilter = TypedEventFilter<DelegateChangedEvent>;

export interface DelegateVotesChangedEventObject {
  account: string;
  oldVotingPower: BigNumber;
  newVotingPower: BigNumber;
}
export type DelegateVotesChangedEvent = TypedEvent<[string, BigNumber, BigNumber], DelegateVotesChangedEventObject>;

export type DelegateVotesChangedEventFilter = TypedEventFilter<DelegateVotesChangedEvent>;

export interface VotingBase extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VotingBaseInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    afterTokenTransfer(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    canVote(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[boolean]>;

    delegate(
      newDelegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    getDelegate(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[string]>;

    getTotalVotingPower(overrides?: CallOverrides): Promise<[BigNumber]>;

    getVotingPower(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  afterTokenTransfer(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  canVote(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>;

  delegate(
    newDelegate: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  getDelegate(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<string>;

  getTotalVotingPower(overrides?: CallOverrides): Promise<BigNumber>;

  getVotingPower(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    afterTokenTransfer(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    canVote(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>;

    delegate(newDelegate: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    getDelegate(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<string>;

    getTotalVotingPower(overrides?: CallOverrides): Promise<BigNumber>;

    getVotingPower(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "DelegateChanged(address,address,address)"(
      delegator?: PromiseOrValue<string> | null,
      currentDelegate?: null,
      newDelegate?: null,
    ): DelegateChangedEventFilter;
    DelegateChanged(
      delegator?: PromiseOrValue<string> | null,
      currentDelegate?: null,
      newDelegate?: null,
    ): DelegateChangedEventFilter;

    "DelegateVotesChanged(address,uint256,uint256)"(
      account?: PromiseOrValue<string> | null,
      oldVotingPower?: null,
      newVotingPower?: null,
    ): DelegateVotesChangedEventFilter;
    DelegateVotesChanged(
      account?: PromiseOrValue<string> | null,
      oldVotingPower?: null,
      newVotingPower?: null,
    ): DelegateVotesChangedEventFilter;
  };

  estimateGas: {
    afterTokenTransfer(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    canVote(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    delegate(
      newDelegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    getDelegate(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    getTotalVotingPower(overrides?: CallOverrides): Promise<BigNumber>;

    getVotingPower(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    afterTokenTransfer(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    canVote(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delegate(
      newDelegate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    getDelegate(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalVotingPower(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVotingPower(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
