/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Mock } from "./ERC20Mock";
export type { NewTelediskoTokenMock } from "./NewTelediskoTokenMock";
export type { ResolutionExecutorMock } from "./ResolutionExecutorMock";
export type { ResolutionManagerV2Mock } from "./ResolutionManagerV2Mock";
export type { ShareholderRegistryMock } from "./ShareholderRegistryMock";
export type { TelediskoTokenMock } from "./TelediskoTokenMock";
export type { TelediskoTokenV2Mock } from "./TelediskoTokenV2Mock";
export type { TokenMock } from "./TokenMock";
export type { VotingMock } from "./VotingMock";
