/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as neokingdomTokenMockSol from "./NeokingdomTokenMock.sol";
import type * as neokingdomTokenV2MockSol from "./NeokingdomTokenV2Mock.sol";
import type * as newTelediskoTokenMockSol from "./NewTelediskoTokenMock.sol";

export type { neokingdomTokenMockSol };

export type { neokingdomTokenV2MockSol };

export type { newTelediskoTokenMockSol };
export type { ERC20Mock } from "./ERC20Mock";
export type { HasRoleMock } from "./HasRoleMock";
export type { ResolutionExecutorMock } from "./ResolutionExecutorMock";
export type { ResolutionManagerV2Mock } from "./ResolutionManagerV2Mock";
export type { ShareholderRegistryMock } from "./ShareholderRegistryMock";
export type { TokenMock } from "./TokenMock";
export type { VotingMock } from "./VotingMock";
