/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DAORoles } from "./DAORoles";
export type { HasRole } from "./HasRole";
export type { ISnapshot } from "./ISnapshot";
export type { Roles } from "./Roles";
export type { Snapshottable } from "./Snapshottable";
