/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { INeokingdomToken } from "./INeokingdomToken";
export type { NeokingdomToken } from "./NeokingdomToken";
