/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { INeokingdomToken__factory } from "./INeokingdomToken__factory";
export { NeokingdomToken__factory } from "./NeokingdomToken__factory";
