/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStdReference__factory } from "./IStdReference__factory";
export { PriceOracle__factory } from "./PriceOracle__factory";
