/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVoting__factory } from "./IVoting__factory";
export { Voting__factory } from "./Voting__factory";
export { VotingBase__factory } from "./VotingBase__factory";
export { VotingSnapshot__factory } from "./VotingSnapshot__factory";
